<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AssemblyName>LoadTest</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NBomber" Version="5.*" />
    <PackageReference Include="NBomber.Http" Version="5.*" />
  </ItemGroup>
</Project>
