version: '3.9'

services:
  mssql:
    # Build from the local Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    image: mssql2022-custom:1.0
    container_name: mssql2022
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123"
    volumes:
      - ./init-db:/init-db
    # Optional: If you want to persist data, you can also mount a volume on /var/opt/mssql
    # volumes:
    #   - mssql_data:/var/opt/mssql

# volumes:
#   mssql_data:
#     driver: local
